language: python
python:
  - "3.8.2"

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="PB_django.settings"

services:
  - postgresql

script:
  - ./manage.py migrate
  - ./manage.py init_db
  - ./manage.py test