# Generated by Django 3.0.3 on 2020-04-02 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('img', models.TextField()),
                ('category', models.TextField()),
                ('stores', models.TextField()),
                ('nutriscore', models.CharField(max_length=1)),
                ('novascore', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urloriginal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='home.Food')),
                ('urlsubstitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='home.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
